server:
  #port: 8087
  port: 8084
  servlet:
    session:
      timeout: 3000


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/learncloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/learncloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    userName: root
    password: ocw35401
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
    redis:
      namespace: test
    timeout: 1800
  redis:
    database: 0
    host: localhost
    port: 6379
    password : lEXYMexSOh0LosjNMo9NtiFK7J26LSMkF3roh5FOLO+y8kZlzCFrVLkwONZBAEHX7cvN3+Zw9gXJRqn0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8   #最大空閒連結
        min-idle: 0   #最小空閒連接




##Line
line.bot:
  channelToken: 'GpQNObkPAwfVKrNAihZQnl1To6V4eH5EA8SIpf9N4NWWTkdI5ip/gN94DRHC+8v4ALHcyeghBdAKrrXf+VzOaKLfoKSyYZje2SrPynruP/frDofFGbSodExX9Q4GvPpltpK2Q4l7Be1kJe4dKGfWxQdB04t89/1O/w1cDnyilFU='
  channelSecret: '2b3f56c1bf5cd86be8e6dd70d62cfc12'



logging:
  level:
    root: info
    com.lrm: debug
    file: logs/debug.log

#引入版本設定
#spring:
#  thymeleaf:
#    mode: HTML
